### ISSUE TITLE
Problem when building with pyinstaller

### ISSUE THREAD

**Issue by ondoheer** [Widdershin/flask-desktop#1]
I loved your Flask Desktop library and am having troubles packaging it with pyinstaller.

I have run into the jinja2 TemplateNotFound Exception issue 
and following the http://stackoverflow.com/questions/35811448/pyinstaller-jinja2-templatenotfound recommendations, I still haven't managed to solve it.

I was wondering if you had a way to do this properly?

**Comment by Popkultur** [comment]
I heard there is a parameter "template_path" for the Flask App, however, since I am using also flask-socketio, this does not work for me.
