### ISSUE TITLE
setting up the desktop app with pyinstaller

### ISSUE THREAD

**Issue by fabines** [Widdershin/flask-desktop#12]
hi,
trying to run the app with pyinstaller but it doesnt work. what do i need to do to make the server run as an exe file?

**Comment by Widdershin** [comment]
When you say that it doesn't work, what goes wrong?

I haven't done this in a long time, I don't really work with Python much anymore. What happens when you run `pyinstaller <your-app.py>`?

**Comment by leynier** [comment]
@fabines we need your answer, if you don't respond I will be forced to close this issue.

**Comment by Nneji123** [comment]
Hello when I try to run the application after compiling with pyinstaller, I get connection refused even if I use 0.0.0.0, localhost or 127.0.0.1 as urls
