### ISSUE TITLE
Un Usable

### ISSUE THREAD

**Issue by A-Trash-Coder** [Widdershin/flask-desktop#18]
Python won't let me install PyQt5, it says Jinja is incompatible, it wont work at all!

**Comment by Widdershin** [comment]
Sorry this isn't maintained, I think there are a few alternative libraries. I might just archive this library unless someone else wants to take it over

**Comment by Pneuro** [comment]
Bummer, this would cut my work down from 2 weeks to 20 minutes. I would take over if I knew enough.
