### ISSUE TITLE
ModuleNotFoundError: No module named 'webui'

### ISSUE THREAD

**Issue by shkhaider2015** [Widdershin/flask-desktop#19]
This is my __init__.py file 
-------------------------
**from webui import WebUI**
from flask import Flask
from application.config import Config

app = Flask(__name__)
app.config.from_object(Config)
ui = WebUI(app, debug=True)
from application import routes

---------------------------
and this is my runnable file

--------------------------

from application import ui

if __name__ == "__main__":
    ui.run()

----------------------------

when I run the application using python run.py I got an error on the first line of __init__.py file.

**Comment by Widdershin** [comment]
Does running `pip install git+git://github.com/widdershin/flask-desktop.git` fix the issue?

**Comment by shkhaider2015** [comment]
yes thanks for replying it fixed the issue
