### ISSUE TITLE
Conflict with  version of werkzeug required 

### ISSUE THREAD

**Issue by RedstonePvP** [Widdershin/flask-desktop#20]
it seems that webui has the werkzeug version set to 0.15.3, there is a bug in that version that gives this error: `TypeError: required field "type_ignores" missing from Module` to fix this all that is needed is an update to that version: [Stackoverflow question](https://stackoverflow.com/questions/60140174/basic-flask-app-not-running-typeerror-required-field-type-ignores-missing-fr). If you could please update the requirements allowing for the update so the issue is resolved

**Comment by Widdershin** [comment]
This module is a bit starved for maintainer attention right now, if you want to make a pull request that would be a great start.

**Comment by Widdershin** [comment]
This got fixed a while ago.
