### ISSUE TITLE
ImportError: cannot import name 'WebUI' from partially initialized module 'webui'

### ISSUE THREAD

**Issue by MPrazzoli** [Widdershin/flask-desktop#24]
I install flask-desktop and the simple exemple: "flask-desktop/examples/test_app.py ", but when I run  it I got the following error:

![immagine](https://user-images.githubusercontent.com/52362087/97298678-15faa780-1854-11eb-81f5-b30b27919e6b.png)

When I run the command:"pip freeze" I can see the package, but still I have the problem I cannot use it.

P.s. I am using Pycharm with anaconda3/python.exe interpreter.

**Comment by Jasperabez** [comment]
Probably you could provide more information on how you install flask-desktop
Did you install the module through `pip install git+git://github.com/widdershin/flask-desktop.git`?

**Comment by MPrazzoli** [comment]
Sorry Jasperabez if I answer just now. I exactely installed the module through pip install git+git://github.com/widdershin/flask-desktop.git taht i saw in the project documentation. I will answer rapidly next time

**Comment by Jasperabez** [comment]
One of your python file is named `webui.py` which conflicts with the actual import of the flask-destop module (called `webui` as well) rename that python file and your issue should be solved.

**Comment by MPrazzoli** [comment]
I have tried right now. I have downloaded through pip install git+git://github.com/widdershin/flask-desktop.git and tried the example which I found in Kelvin article: "https://medium.com/@KelvinMwinuka/converting-flask-web-app-into-a-cross-platform-desktop-app-6692bf0720c" but have this message error.

![immagine](https://user-images.githubusercontent.com/52362087/97875382-9751ae80-1d1a-11eb-946e-a9e4ed1ed3ea.png)
