### ISSUE TITLE
PyQt5 dependency is licenced under the GPL v3 license so flask-desktop cannot use MIT

### ISSUE THREAD

**Issue by JonThom** [Widdershin/flask-desktop#35]
What it says in the issue title. 
See https://pypi.org/project/PyQt5/

**Comment by Widdershin** [comment]
🤦 Thanks for bringing this to my attention, I knew there was a reason I used pyside back in the day.

I've switched to using PySide2 in 6aeb656, that should resolve the licensing issue as far as I can see.

**Comment by JonThom** [comment]
Ah, I was going by the readme but just saw the commit you are referring to - nice!
