### ISSUE TITLE
pip install webui -  Failed to find MSCV 10

### ISSUE THREAD

**Issue by ClimenteA** [Widdershin/flask-desktop#5]
Hello, 
At the first look at the description text for this module I was WOW just what I was looking for :)

I'm trying to install it on a Windows 7(64bit), Python 3.4.4(64bit). I have installed Microsoft Visual C++ 2010(x64 and x86).

I tried to install separately PySide but I got the same error even if PySide is installed. 

This is what I get:

Collecting pyside==1.2.1 (from WebUI)
  Using cached PySide-1.2.1.tar.gz
Installing collected packages: pyside, WebUI
  Running setup.py install for pyside ... error
    Complete output from command c:\python34\python.exe -u -c "import setuptools
, tokenize;__file__='C:\\Users\\ALINCM~1\\AppData\\Local\\Temp\\pip-build-zad1xx
li\\pyside\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().
replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install -
-record C:\Users\ALINCM~1\AppData\Local\Temp\pip-xf08osxu-record\install-record.
txt --single-version-externally-managed --compile:
    Removing C:\Users\ALINCM~1\AppData\Local\Temp\pip-build-zad1xxli\pyside\pysi
de_package
    running install
    running build
    Python architecture is 64bit
    nmake not found. Trying to initialize the MSVC env...
    Searching MSVC compiler version 10.0
    error: Failed to find the MSVC compiler version 10.0 on your system.

Is there a quick fix for this? 
I'm not using a compatible Python version?

Thank you for your work

**Comment by mstuttgart** [comment]
I get this same error. Try install with:
```
pip install git+https://github.com/Widdershin/flask-desktop.git
```
This commando install WebUi directly from git repository (use PyQt5). It seems, the pypi version is outdated, using PySide (that require extra dependencies).

**Comment by ClimenteA** [comment]
Tried using "pip install git+https://github.com/Widdershin/flask-desktop.git", it didn't work, so I copied as zip the entire repository and run "python setup.py install" - didn't work either.

Most probably it's because I use Python 3.4 (compatibility reasons), I saw that PyQT5 it's for Python 3.5 and up.

When I'll move to a bigger version than Python 3.4, I think I will not have this problem anymore :)
